### ISSUE TITLE
基于Fragment的界面怎么处理？

### ISSUE THREAD

**Issue by ggggxiaolong** [zybieku/SoftKeyboardUtil#2]
Fragment 没有dispatchTouchEvent这个方法，怎么处理呢？

**Comment by zybieku** [comment]
和Activity一样啦,也是只要一个方法,就是在Fragment中写一个不是重写的public方法hideSoftByEditViewIds()传入你EditText,然后再到Acitvity中的hideSoftByEditViewIds方法中调用fragment.hideSoftByEditViewIds()就可以啦

**Comment by zybieku** [comment]
@ggggxiaolong Fragment是Attach到Activity的,他们共用的是一个dispatchTouchEvent方法,所有处理的方法是在hideSoftByEditViewIds()方法,再调用Fragment的hideSoftByEditViewIds()方法,(Fragment中的方法名字随便取,主要作用就是把Fragment中的EditText传入到这个方法就成啦)

**Comment by ggggxiaolong** [comment]
为什么要清空焦点呢？  而且清空焦点的代码不需要在判断一次，直接清空就可以了吧

**Comment by zybieku** [comment]
我的想法是,当editText获取焦点的时, 软键盘会自动弹出,当我点击其他地方的时候,软键盘就被强制隐藏了,如果我不把他清除掉,下次点击就会出问题,当然如果可以改进更好,欢迎帮忙
