### ISSUE TITLE
两个EditText，一个Button，点击Button不会隐藏键盘，点击空白隐藏键盘，并且焦点从第二个跳到第一个EditText

### ISSUE THREAD

**Issue by SiberiaDante** [zybieku/SoftKeyboardUtil#5]
两个EditText，一个Button，点击Button不会隐藏键盘，点击空白隐藏键盘，并且焦点从第二个跳到第一个EditText;测试手机华为荣耀4.4.2

**Comment by zybieku** [comment]
大佬是否对button进行过滤操作了. 后面的问题,你把默认的焦点不要给第一个editText,就不会焦点跳转了

**Comment by zybieku** [comment]
@SiberiaDante 大佬是否对button进行过滤操作了. 后面的问题,你把默认的焦点不要给第一个editText,就不会焦点跳转了

**Comment by SiberiaDante** [comment]
我的代码如下：Activity继承的是BaseActivity里面复制的你得代码没有别的多余额操作
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <EditText
        android:id="@+id/edt_one"
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:layout_marginBottom="10dp"
        android:hint="第一个编辑框"
        tools:layout_editor_absoluteX="8dp" />

    <EditText
        android:id="@+id/edt_two"
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:layout_marginBottom="10dp"
        android:hint="第二个编辑框" />

    <Button
        android:id="@+id/btn_one"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />
</LinearLayout>

private EditText mEdtOne, mEdtTwo;
    private View mBtnOne;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_key_board);
        mEdtOne = (EditText) findViewById(R.id.edt_one);
        mEdtTwo = (EditText) findViewById(R.id.edt_two);
        mBtnOne = findViewById(R.id.btn_one);
    }

    @Override
    public View[] filterViewByIds() {
        View[] views = {mBtnOne};
        return views;
    }

    @Override
    public int[] hideSoftByEditViewIds() {
        int[] ids = {R.id.edt_one, R.id.edt_two};
        return ids;
    }

**Comment by zybieku** [comment]
@SiberiaDante 你好,如果你不需要过滤,大佬不需要重写这个方法,你这里传入了button对象,所有就把button给过滤掉,所以就失效了.
 @Override
public View[] filterViewByIds() {
    View[] views = {mBtnOne};
    return views;
}
还有焦点的问题 你在看在xml布局里面默认把焦点给editText父布局,详情可以看我的博客,最后的介绍

**Comment by zybieku** [comment]
@SiberiaDante filterViewByIds()这个方法,是用来过滤掉某个控件失效的,这是针对一些特殊的情况使用的,如果大佬您不需要,请把他给删掉,只要hideSoftByEditViewIds()方法里的一行代码就可以了

**Comment by SiberiaDante** [comment]
完美解决，感谢大神，代码复制走了，star感谢！
