### ISSUE TITLE
对Fragment&WebView的支持

### ISSUE THREAD

**Issue by Jiiiiiin** [zybieku/SoftKeyboardUtil#7]
如果想做好的话，其实对Fragment的支持是必须的；
其次混合开发目前很多，对于WebView中 输入框的键盘遮挡问题也很重要，做好这个应该很加分。

@zybieku 加油

**Comment by zybieku** [comment]
@Jiiiiiin 继承的方式是可以支持fragment的,至于webview中输入框的遮挡问题,这个让开发者自己根据自己项目的需求定制会更好

**Comment by Jiiiiiin** [comment]
@zybieku 可以只是fragment么？ 我试试看

**Comment by Jiiiiiin** [comment]
#8 写了一下 你看看可否

**Comment by zybieku** [comment]
我就不看了哈，我都没有Android环境了，大佬，有伙计提出你那个内存泄漏了，他修改过，我现在又把你的覆盖了他的了，你麻烦再看下。。。，再修改

**Comment by zybieku** [comment]
@Jiiiiiin 你这给我就直接合了

**Comment by zybieku** [comment]
@Jiiiiiin 你这个我就直接合了，覆盖了以前的，你再看看其他伙计提的issue,有一个地方确实有内存泄漏
